use std::collections::{HashMap, HashSet};
use std::fs;
use std::io::{BufRead, BufReader};
use std::path::{Path, PathBuf};
use std::time::SystemTime;

use chrono::{DateTime, Utc};
use serde_json::Value;

use super::models::JsonlEntry;
use super::models::{Project, Session};
use super::paths::{decode_project_path, get_claude_dir, normalize_path_for_comparison};

pub struct ProjectStore {
    claude_dir: PathBuf,
}

pub struct BatchDeleteOutcome {
    pub deleted_count: usize,
    pub failed_count: usize,
    pub errors: Vec<String>,
}

#[derive(Debug, Default)]
pub(crate) struct SessionSummary {
    pub first_message: Option<String>,
    pub first_message_timestamp: Option<String>,
    pub last_message_timestamp: Option<String>,
    pub model: Option<String>,
    pub has_message_entry: bool,
}

const MAX_SESSION_SUMMARY_SCAN_LINES: usize = 200;
const MAX_PROJECT_PATH_SCAN_FILES: usize = 20;
const MAX_PROJECT_PATH_SCAN_LINES: usize = 10;

pub(crate) fn is_displayable_user_text(text: &str) -> bool {
    if text.trim().is_empty() {
        return false;
    }
    if text.contains(
        "Caveat: The messages below were generated by the user while running local commands",
    ) {
        return false;
    }
    if text.starts_with("<command-name>") || text.starts_with("<local-command-stdout>") {
        return false;
    }
    if text.contains("Warmup") {
        return false;
    }
    if is_slash_command_message(text) || is_auto_compaction_instruction(text) {
        return false;
    }
    true
}

fn is_slash_command_message(text: &str) -> bool {
    let trimmed = text.trim();
    trimmed.starts_with('/')
        && !trimmed.contains('\n')
        && trimmed.len() < 256
        && !trimmed.contains('\\')
        && trimmed.matches('/').count() == 1
}

fn is_auto_compaction_instruction(text: &str) -> bool {
    let normalized = text
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .to_lowercase();

    normalized.starts_with(
        "focus on preserving key information, decisions made, and current context.",
    ) || normalized.starts_with(
        "preserve only the most critical information: current task, key decisions, and essential context.",
    ) || normalized.starts_with(
        "maintain comprehensive context while removing only obvious redundancies.",
    )
}

pub(crate) fn extract_text_content(content_value: &Value) -> Option<String> {
    if let Some(text) = content_value.as_str() {
        if is_displayable_user_text(text) {
            return Some(text.to_string());
        }
        return None;
    }

    let mut extracted = String::new();
    let mut has_text = false;
    for item in content_value.as_array()? {
        if item.get("type").and_then(|t| t.as_str()) == Some("text") {
            if let Some(text) = item.get("text").and_then(|t| t.as_str()) {
                extracted.push_str(text);
                has_text = true;
            }
        }
    }

    if has_text && is_displayable_user_text(&extracted) {
        Some(extracted)
    } else {
        None
    }
}

pub(crate) fn extract_session_summary(path: &Path) -> SessionSummary {
    let file = match fs::File::open(path) {
        Ok(file) => file,
        Err(_) => return SessionSummary::default(),
    };

    let reader = BufReader::new(file);
    let mut summary = SessionSummary {
        last_message_timestamp: fs::metadata(path)
            .ok()
            .and_then(|metadata| metadata.modified().ok())
            .map(|modified| DateTime::<Utc>::from(modified).to_rfc3339()),
        ..SessionSummary::default()
    };

    for line in reader
        .lines()
        .map_while(Result::ok)
        .take(MAX_SESSION_SUMMARY_SCAN_LINES)
    {
        if line.trim().is_empty() {
            continue;
        }

        let value = match serde_json::from_str::<Value>(&line) {
            Ok(value) => value,
            Err(_) => continue,
        };

        if summary.model.is_none() && value.get("model").and_then(|m| m.as_str()).is_some() {
            summary.model = value
                .get("model")
                .and_then(|m| m.as_str())
                .map(str::to_string);
        } else if summary.model.is_none() {
            if let Some(message) = value.get("message") {
                if let Some(model) = message.get("model").and_then(|m| m.as_str()) {
                    summary.model = Some(model.to_string());
                }
            }
        }

        if summary.first_message.is_none() {
            if let Ok(entry) = serde_json::from_value::<JsonlEntry>(value.clone()) {
                if let Some(message) = entry.message {
                    if message.role.as_deref() == Some("user") {
                        if let Some(content_value) = message.content {
                            if let Some(text) = extract_text_content(&content_value) {
                                summary.first_message = Some(text);
                                summary.first_message_timestamp = entry.timestamp;
                            }
                        }
                    }
                }
            }
        }

        if value.get("message").is_some() {
            summary.has_message_entry = true;
            if summary.last_message_timestamp.is_none() {
                if let Some(ts) = value.get("timestamp").and_then(|t| t.as_str()) {
                    summary.last_message_timestamp = Some(ts.to_string());
                }
            }
        }

        if summary.first_message.is_some() && summary.model.is_some() {
            break;
        }
    }

    summary
}

impl ProjectStore {
    pub fn new() -> Result<Self, String> {
        let claude_dir = get_claude_dir().map_err(|e| e.to_string())?;
        Ok(Self { claude_dir })
    }

    #[cfg(test)]
    pub fn from_claude_dir_for_tests(claude_dir: PathBuf) -> Self {
        Self { claude_dir }
    }

    pub fn list_projects(&self) -> Result<Vec<Project>, String> {
        log::info!("Listing projects from ~/.claude/projects");

        let mut all_projects = Vec::new();
        let projects_dir = self.projects_dir();
        let mut hidden_projects = self.load_hidden_projects()?;

        if projects_dir.exists() {
            // 一次性收集目录项，避免重复 read_dir 同一目录（原先扫描两遍：一遍计数、一遍遍历）。
            let entries: Vec<_> = fs::read_dir(&projects_dir)
                .map_err(|e| format!("Failed to read projects directory: {}", e))?
                .filter_map(|e| e.ok())
                .collect();

            // Count total valid project directories first
            let total_project_count = entries.iter().filter(|e| e.path().is_dir()).count();

            // Safety check: if hidden_projects would hide ALL projects, clear the hidden list
            // This prevents the "no projects found" issue caused by corrupted hidden_projects.json
            if total_project_count > 0 && hidden_projects.len() >= total_project_count {
                log::warn!(
                    "Safety check triggered: hidden_projects ({}) >= total projects ({}). Clearing hidden list to prevent all projects from being hidden.",
                    hidden_projects.len(),
                    total_project_count
                );
                // Clear the hidden projects file
                if let Err(e) = self.save_hidden_projects(&[]) {
                    log::error!("Failed to clear hidden projects file: {}", e);
                }
                hidden_projects.clear();
            }

            for entry in entries {
                let path = entry.path();

                if path.is_dir() {
                    let dir_name = path
                        .file_name()
                        .and_then(|n| n.to_str())
                        .ok_or_else(|| "Invalid directory name".to_string())?;

                    if hidden_projects.contains(&dir_name.to_string()) {
                        log::debug!("Skipping hidden project: {}", dir_name);
                        continue;
                    }

                    let metadata = fs::metadata(&path)
                        .map_err(|e| format!("Failed to read directory metadata: {}", e))?;

                    let created_at = metadata
                        .created()
                        .or_else(|_| metadata.modified())
                        .unwrap_or(SystemTime::UNIX_EPOCH)
                        .duration_since(SystemTime::UNIX_EPOCH)
                        .unwrap_or_default()
                        .as_secs();

                    let project_path = match get_project_path_from_sessions(&path) {
                        Ok(path) => path,
                        Err(e) => {
                            log::warn!(
                                "Failed to get project path from sessions for {}: {}, falling back to decode",
                                dir_name,
                                e
                            );
                            decode_project_path(dir_name)
                        }
                    };

                    let mut session_infos: Vec<(String, u64)> = Vec::new();
                    let mut latest_activity = created_at;

                    if let Ok(session_entries) = fs::read_dir(&path) {
                        for session_entry in session_entries.flatten() {
                            let session_path = session_entry.path();
                            if session_path.is_file()
                                && session_path.extension().and_then(|s| s.to_str())
                                    == Some("jsonl")
                            {
                                if let Some(session_id) =
                                    session_path.file_stem().and_then(|s| s.to_str())
                                {
                                    if session_id.starts_with("agent-") {
                                        continue;
                                    }

                                    if let Ok(session_metadata) = fs::metadata(&session_path) {
                                        let session_modified = session_metadata
                                            .modified()
                                            .unwrap_or(SystemTime::UNIX_EPOCH)
                                            .duration_since(SystemTime::UNIX_EPOCH)
                                            .unwrap_or_default()
                                            .as_secs();

                                        if session_modified > latest_activity {
                                            latest_activity = session_modified;
                                        }

                                        session_infos
                                            .push((session_id.to_string(), session_modified));
                                    }
                                }
                            }
                        }
                    }

                    session_infos.sort_by(|a, b| b.1.cmp(&a.1));
                    let sessions: Vec<String> = session_infos
                        .into_iter()
                        .map(|(session_id, _)| session_id)
                        .collect();

                    // Claude 计数 = 本地 JSONL 会话数；Codex/Gemini 在 command 层统一补齐。
                    let claude_count = sessions.len() as u32;

                    all_projects.push(Project {
                        id: dir_name.to_string(),
                        path: project_path,
                        sessions,
                        created_at: latest_activity,
                        session_counts: super::models::SessionCounts {
                            claude: claude_count,
                            codex: 0,
                            gemini: 0,
                        },
                    });
                }
            }
        } else {
            log::warn!("Projects directory does not exist: {:?}", projects_dir);
        }

        self.deduplicate_projects(all_projects, hidden_projects.len())
    }

    pub fn get_project_sessions(&self, project_id: &str) -> Result<Vec<Session>, String> {
        log::info!("Getting sessions for project: {}", project_id);

        let project_dir = self.projects_dir().join(project_id);
        let todos_dir = self.todos_dir();

        if !project_dir.exists() {
            return Err(format!("Project directory not found: {}", project_id));
        }

        let project_path = match get_project_path_from_sessions(&project_dir) {
            Ok(path) => path,
            Err(e) => {
                log::warn!(
                    "Failed to get project path from sessions for {}: {}, falling back to decode",
                    project_id,
                    e
                );
                decode_project_path(project_id)
            }
        };

        let mut sessions = Vec::new();
        let entries = fs::read_dir(&project_dir)
            .map_err(|e| format!("Failed to read project directory: {}", e))?;

        for entry in entries {
            let entry = entry.map_err(|e| format!("Failed to read directory entry: {}", e))?;
            let path = entry.path();

            if path.is_file() && path.extension().and_then(|s| s.to_str()) == Some("jsonl") {
                if let Some(session_id) = path.file_stem().and_then(|s| s.to_str()) {
                    // 🔧 Skip agent-*.jsonl files (subagent sessions)
                    if session_id.starts_with("agent-") {
                        continue;
                    }
                    let metadata = fs::metadata(&path)
                        .map_err(|e| format!("Failed to read file metadata: {}", e))?;

                    let created_at = metadata
                        .created()
                        .or_else(|_| metadata.modified())
                        .unwrap_or(SystemTime::UNIX_EPOCH)
                        .duration_since(SystemTime::UNIX_EPOCH)
                        .unwrap_or_default()
                        .as_secs();

                    let summary = extract_session_summary(&path);

                    // ✅ Fallback: 如果 first_message 为空，使用默认文本以确保会话能显示
                    // 这样即使所有用户消息都被过滤掉，会话仍然可见
                    let first_message = summary.first_message.or_else(|| {
                        // 检查会话是否真的有内容：
                        // 1. 有 last_message_timestamp，说明有消息
                        // 2. 文件大小 > 100 字节（排除几乎空的会话文件）
                        let has_content = summary.has_message_entry
                            && path.metadata().ok().map(|m| m.len() > 100).unwrap_or(false);

                        if has_content {
                            // 只显示 session_id 的前8位，避免 UI 过长
                            let short_id = if session_id.len() >= 8 {
                                &session_id[..8]
                            } else {
                                session_id
                            };
                            Some(format!("Resumed Session ({}...)", short_id))
                        } else {
                            // 真正的空会话
                            None
                        }
                    });

                    if first_message.is_none() {
                        log::debug!("Skipping non-displayable utility session: {}", session_id);
                        continue;
                    }

                    let todo_path = todos_dir.join(format!("{}.json", session_id));
                    let todo_data = if todo_path.exists() {
                        fs::read_to_string(&todo_path)
                            .ok()
                            .and_then(|content| serde_json::from_str::<Value>(&content).ok())
                    } else {
                        None
                    };

                    sessions.push(Session {
                        id: session_id.to_string(),
                        project_id: project_id.to_string(),
                        project_path: project_path.clone(),
                        todo_data,
                        created_at,
                        first_message,
                        message_timestamp: summary.first_message_timestamp,
                        last_message_timestamp: summary.last_message_timestamp,
                        model: summary.model,
                    });
                }
            }
        }

        sessions.sort_by(|a, b| b.created_at.cmp(&a.created_at));
        Ok(sessions)
    }

    pub fn delete_session(&self, project_id: &str, session_id: &str) -> Result<bool, String> {
        log::info!(
            "Deleting session {} from project {}",
            session_id,
            project_id
        );

        let mut session_deleted = false;

        let session_file = self
            .projects_dir()
            .join(project_id)
            .join(format!("{}.jsonl", session_id));

        if session_file.exists() {
            fs::remove_file(&session_file)
                .map_err(|e| format!("Failed to delete session file: {}", e))?;
            log::info!("Deleted session file: {:?}", session_file);
            session_deleted = true;
        } else {
            log::warn!("Session file not found: {:?}", session_file);
        }

        let todo_file = self
            .claude_dir
            .join("todos")
            .join(format!("{}.json", session_id));

        if todo_file.exists() {
            fs::remove_file(&todo_file)
                .map_err(|e| format!("Failed to delete TODO file: {}", e))?;
            log::info!("Deleted TODO file: {:?}", todo_file);
        }

        let git_records_file = self
            .claude_dir
            .join("sessions")
            .join(project_id)
            .join(format!("{}.git-records.json", session_id));

        if git_records_file.exists() {
            if let Err(e) = fs::remove_file(&git_records_file) {
                log::warn!(
                    "Failed to delete git records file for {}: {}",
                    session_id,
                    e
                );
            } else {
                log::info!("Deleted git records file: {:?}", git_records_file);
            }
        }

        Ok(session_deleted)
    }

    pub fn delete_sessions_batch(
        &self,
        project_id: &str,
        session_ids: &[String],
    ) -> BatchDeleteOutcome {
        let mut deleted_count = 0;
        let mut failed_count = 0;
        let mut errors = Vec::new();

        for session_id in session_ids {
            match self.delete_session(project_id, session_id) {
                Ok(session_deleted) => {
                    if session_deleted {
                        deleted_count += 1;
                    } else {
                        failed_count += 1;
                        errors.push(format!("Session file not found for ID: {}", session_id));
                    }
                }
                Err(e) => {
                    failed_count += 1;
                    errors.push(format!("Failed to delete session {}: {}", session_id, e));
                }
            }
        }

        BatchDeleteOutcome {
            deleted_count,
            failed_count,
            errors,
        }
    }

    pub fn hide_project(&self, project_id: &str) -> Result<bool, String> {
        let mut hidden_projects = self.load_hidden_projects()?;
        if hidden_projects.contains(&project_id.to_string()) {
            return Ok(false);
        }

        hidden_projects.push(project_id.to_string());
        self.save_hidden_projects(&hidden_projects)?;
        Ok(true)
    }

    pub fn restore_project(&self, project_id: &str) -> Result<(), String> {
        let mut hidden_projects = self.load_hidden_projects()?;

        if let Some(pos) = hidden_projects.iter().position(|x| x == project_id) {
            hidden_projects.remove(pos);
            self.save_hidden_projects(&hidden_projects)?;
            Ok(())
        } else {
            Err(format!(
                "Project '{}' is not in the hidden list",
                project_id
            ))
        }
    }

    pub fn delete_project_permanently(&self, project_id: &str) -> Result<String, String> {
        log::info!("Permanently deleting project: {}", project_id);

        let projects_dir = self.projects_dir();
        let project_dir = projects_dir.join(project_id);

        let mut actual_project_dir = None;
        let mut actual_project_id = project_id.to_string();

        if project_dir.exists() {
            actual_project_dir = Some(project_dir);
        } else if let Ok(entries) = fs::read_dir(&projects_dir) {
            let target_normalized_path =
                normalize_path_for_comparison(&decode_project_path(project_id));

            for entry in entries.flatten() {
                if entry.path().is_dir() {
                    if let Some(dir_name) = entry.file_name().to_str() {
                        let candidate_path = match get_project_path_from_sessions(&entry.path()) {
                            Ok(path) => path,
                            Err(_) => decode_project_path(dir_name),
                        };

                        if normalize_path_for_comparison(&candidate_path) == target_normalized_path
                        {
                            actual_project_dir = Some(entry.path());
                            actual_project_id = dir_name.to_string();
                            log::info!(
                                "Found actual project directory: {} -> {}",
                                project_id,
                                actual_project_id
                            );
                            break;
                        }
                    }
                }
            }
        }

        let dir_to_delete = actual_project_dir.ok_or_else(|| {
            if project_id.contains("--") && !project_id.contains("---") {
                format!(
                    "项目目录不存在。可能已被手动删除，或使用了不同的编码格式。原始ID: {}",
                    project_id
                )
            } else {
                format!("项目目录不存在: {:?}", projects_dir.join(project_id))
            }
        })?;

        fs::remove_dir_all(&dir_to_delete)
            .map_err(|e| format!("Failed to delete project directory: {}", e))?;

        self.remove_from_hidden_projects(&[project_id, &actual_project_id])?;

        Ok(actual_project_id)
    }

    pub fn list_hidden_projects(&self) -> Result<Vec<String>, String> {
        log::info!("Listing hidden projects with directory validation");

        let mut hidden_projects = self.load_hidden_projects()?;
        let projects_dir = self.projects_dir();

        let mut validated_hidden_projects = Vec::new();
        let mut projects_to_remove = Vec::new();

        for hidden_project_id in &hidden_projects {
            let project_dir = projects_dir.join(hidden_project_id);

            if project_dir.exists() {
                validated_hidden_projects.push(hidden_project_id.clone());
                log::debug!("Hidden project directory exists: {}", hidden_project_id);
            } else {
                let normalized_path =
                    normalize_path_for_comparison(&decode_project_path(hidden_project_id));
                let mut found_match = false;

                if let Ok(entries) = fs::read_dir(&projects_dir) {
                    for entry in entries.flatten() {
                        if entry.path().is_dir() {
                            if let Some(dir_name) = entry.file_name().to_str() {
                                let candidate_path =
                                    match get_project_path_from_sessions(&entry.path()) {
                                        Ok(path) => path,
                                        Err(_) => decode_project_path(dir_name),
                                    };

                                if normalize_path_for_comparison(&candidate_path) == normalized_path
                                {
                                    validated_hidden_projects.push(dir_name.to_string());
                                    log::debug!(
                                        "Found matching directory for hidden project {} -> {}",
                                        hidden_project_id,
                                        dir_name
                                    );
                                    found_match = true;
                                    break;
                                }
                            }
                        }
                    }
                }

                if !found_match {
                    log::warn!(
                        "Hidden project directory not found (will remove from list): {}",
                        hidden_project_id
                    );
                    projects_to_remove.push(hidden_project_id.clone());
                }
            }
        }

        if !projects_to_remove.is_empty() {
            hidden_projects.retain(|id| !projects_to_remove.contains(id));
            self.save_hidden_projects(&hidden_projects)?;
            log::info!(
                "Removed {} invalid hidden projects",
                projects_to_remove.len()
            );
        }

        Ok(validated_hidden_projects)
    }

    fn projects_dir(&self) -> PathBuf {
        self.claude_dir.join("projects")
    }

    fn todos_dir(&self) -> PathBuf {
        self.claude_dir.join("todos")
    }

    fn load_hidden_projects(&self) -> Result<Vec<String>, String> {
        let hidden_projects_file = self.hidden_projects_file();

        if hidden_projects_file.exists() {
            let content = fs::read_to_string(&hidden_projects_file)
                .map_err(|e| format!("Failed to read hidden projects file: {}", e))?;
            Ok(serde_json::from_str(&content).unwrap_or_else(|_| Vec::new()))
        } else {
            Ok(Vec::new())
        }
    }

    fn save_hidden_projects(&self, projects: &[String]) -> Result<(), String> {
        let hidden_projects_file = self.hidden_projects_file();
        let content = serde_json::to_string_pretty(projects)
            .map_err(|e| format!("Failed to serialize hidden projects: {}", e))?;
        fs::write(&hidden_projects_file, content)
            .map_err(|e| format!("Failed to write hidden projects file: {}", e))
    }

    fn hidden_projects_file(&self) -> PathBuf {
        self.claude_dir.join("hidden_projects.json")
    }

    fn deduplicate_projects(
        &self,
        all_projects: Vec<Project>,
        hidden_count: usize,
    ) -> Result<Vec<Project>, String> {
        let original_count = all_projects.len();
        let mut unique_projects_map: HashMap<String, Project> = HashMap::new();

        for project in all_projects {
            let normalized_path = normalize_path_for_comparison(&project.path);

            match unique_projects_map.get_mut(&normalized_path) {
                Some(existing_project) => {
                    log::debug!(
                        "Merging duplicate project with path: {} (existing: {}, new: {})",
                        project.path,
                        existing_project.id,
                        project.id
                    );

                    let mut new_sessions = project.sessions;
                    for session in new_sessions.drain(..) {
                        if !existing_project.sessions.contains(&session) {
                            existing_project.sessions.push(session);
                        }
                    }

                    if project.created_at > existing_project.created_at {
                        existing_project.created_at = project.created_at;
                    }

                    let should_update_id = project.id.len() < existing_project.id.len()
                        || (project.id.len() == existing_project.id.len()
                            && !project.id.contains("--")
                            && existing_project.id.contains("--"))
                        || (project.id.len() == existing_project.id.len()
                            && project.id.chars().any(|c| c.is_uppercase())
                            && existing_project.id.chars().all(|c| !c.is_uppercase()));

                    if should_update_id {
                        log::debug!(
                            "Updating project ID from '{}' to '{}'",
                            existing_project.id,
                            project.id
                        );
                        existing_project.id = project.id;
                    }
                }
                None => {
                    unique_projects_map.insert(normalized_path, project);
                }
            }
        }

        let mut unique_projects: Vec<Project> = unique_projects_map
            .into_values()
            .map(|mut project| {
                let mut unique_sessions = HashSet::new();
                project
                    .sessions
                    .retain(|session| unique_sessions.insert(session.clone()));
                // 合并/去重会改变 Claude 会话集合，同步 claude 计数避免与 sessions 不一致。
                project.session_counts.claude = project.sessions.len() as u32;
                project
            })
            .collect();

        unique_projects.sort_by(|a, b| b.created_at.cmp(&a.created_at));

        log::info!(
            "Found {} unique projects (filtered {} hidden, {} duplicates)",
            unique_projects.len(),
            hidden_count,
            original_count - unique_projects.len()
        );

        Ok(unique_projects)
    }

    fn remove_from_hidden_projects(&self, project_ids: &[&str]) -> Result<(), String> {
        let hidden_projects_file = self.hidden_projects_file();
        if hidden_projects_file.exists() {
            let mut hidden_projects = self.load_hidden_projects()?;
            let original_len = hidden_projects.len();
            hidden_projects.retain(|id| !project_ids.contains(&id.as_str()));

            if hidden_projects.len() != original_len {
                self.save_hidden_projects(&hidden_projects)?;
                log::info!(
                    "Removed project(s) from hidden list: {}",
                    project_ids.join(", ")
                );
            }
        }
        Ok(())
    }

    /// 按真实路径解除隐藏：把指定路径对应的（已被 delete_project 隐藏的）项目从 hidden 列表移除。
    /// 用于"重新添加曾删除过的项目"——隐藏列表存的是目录名（编码后），需把每个隐藏项解析回真实
    /// 路径再与目标路径归一化比对，命中即移除。复用 delete_project_permanently 的同款匹配思路。
    /// 返回是否确有项目被恢复。
    pub fn restore_project_by_path(&self, project_path: &str) -> Result<bool, String> {
        let hidden_projects = self.load_hidden_projects()?;
        if hidden_projects.is_empty() {
            return Ok(false);
        }

        let target_normalized = normalize_path_for_comparison(project_path);
        let projects_dir = self.projects_dir();
        let mut to_restore: Vec<String> = Vec::new();

        for hidden_id in &hidden_projects {
            // 隐藏项的真实路径：优先从其会话 cwd 解析，目录不存在/无会话时回退到目录名解码。
            let candidate_dir = projects_dir.join(hidden_id);
            let candidate_path = match get_project_path_from_sessions(&candidate_dir) {
                Ok(path) => path,
                Err(_) => decode_project_path(hidden_id),
            };

            if normalize_path_for_comparison(&candidate_path) == target_normalized {
                to_restore.push(hidden_id.clone());
            }
        }

        if to_restore.is_empty() {
            return Ok(false);
        }

        let refs: Vec<&str> = to_restore.iter().map(|s| s.as_str()).collect();
        self.remove_from_hidden_projects(&refs)?;
        log::info!(
            "Restored project(s) by path '{}': {}",
            project_path,
            to_restore.join(", ")
        );
        Ok(true)
    }
}

fn get_project_path_from_sessions(project_dir: &Path) -> Result<String, String> {
    let mut jsonl_paths: Vec<(PathBuf, u64)> = fs::read_dir(project_dir)
        .map_err(|e| format!("Failed to read project directory: {}", e))?
        .filter_map(Result::ok)
        .filter_map(|entry| {
            let path = entry.path();
            if !(path.is_file() && path.extension().and_then(|s| s.to_str()) == Some("jsonl")) {
                return None;
            }
            let modified = fs::metadata(&path)
                .ok()
                .and_then(|metadata| metadata.modified().ok())
                .and_then(|modified| modified.duration_since(SystemTime::UNIX_EPOCH).ok())
                .map(|duration| duration.as_secs())
                .unwrap_or(0);
            Some((path, modified))
        })
        .collect();

    jsonl_paths.sort_by(|a, b| b.1.cmp(&a.1));

    for (path, _) in jsonl_paths.into_iter().take(MAX_PROJECT_PATH_SCAN_FILES) {
        if let Ok(file) = fs::File::open(&path) {
            let reader = BufReader::new(file);
            for line in reader
                .lines()
                .map_while(Result::ok)
                .take(MAX_PROJECT_PATH_SCAN_LINES)
            {
                if let Ok(json) = serde_json::from_str::<serde_json::Value>(&line) {
                    if let Some(cwd) = json.get("cwd").and_then(|v| v.as_str()) {
                        let cleaned_cwd = cwd.replace("\\\\", "\\");

                        // On macOS, avoid canonicalize() as it resolves symlinks and can cause
                        // path mismatches (e.g., /tmp -> /private/tmp, /var -> /private/var)
                        // Also, canonicalize() fails if the path doesn't exist (project moved/deleted)
                        #[cfg(target_os = "macos")]
                        let normalized_cwd = normalize_macos_path(&cleaned_cwd);

                        #[cfg(target_os = "windows")]
                        let normalized_cwd = Path::new(&cleaned_cwd)
                            .canonicalize()
                            .map(|p| {
                                let path_str = p.to_string_lossy().to_string();
                                // Remove Windows long path prefix (\\?\)
                                if path_str.starts_with("\\\\?\\") {
                                    path_str[4..].to_string()
                                } else {
                                    path_str
                                }
                            })
                            .unwrap_or_else(|_| cleaned_cwd.clone());

                        #[cfg(not(any(target_os = "macos", target_os = "windows")))]
                        let normalized_cwd = cleaned_cwd.clone();

                        return Ok(normalized_cwd);
                    }
                }
            }
        }
    }

    if let Some(path) = project_dir.file_name().and_then(|name| name.to_str()) {
        Ok(decode_project_path(path))
    } else {
        Err("Could not determine project path from session files".to_string())
    }
}

/// Normalize macOS paths without using canonicalize()
/// This avoids issues with:
/// 1. Symlink resolution (e.g., /tmp -> /private/tmp)
/// 2. Non-existent paths (project moved/deleted)
/// 3. iCloud Drive and other special paths
#[cfg(target_os = "macos")]
fn normalize_macos_path(path: &str) -> String {
    let mut normalized = path.to_string();

    // Remove /private prefix if present (macOS symlink target)
    // This ensures consistency: /private/tmp and /tmp should be treated the same
    if normalized.starts_with("/private/tmp/") {
        normalized = normalized.replacen("/private/tmp/", "/tmp/", 1);
    } else if normalized.starts_with("/private/var/") {
        normalized = normalized.replacen("/private/var/", "/var/", 1);
    } else if normalized.starts_with("/private/etc/") {
        normalized = normalized.replacen("/private/etc/", "/etc/", 1);
    }

    // Remove trailing slash if present (except for root)
    if normalized.len() > 1 && normalized.ends_with('/') {
        normalized.pop();
    }

    normalized
}

#[cfg(test)]
mod tests {
    use super::{extract_session_summary, ProjectStore};
    use std::fs;

    #[test]
    fn list_projects_uses_metadata_without_requiring_displayable_prompt() {
        let tmp = tempfile::tempdir().unwrap();
        let claude_dir = tmp.path().join(".claude");
        let project_dir = claude_dir.join("projects").join("demo-project");
        fs::create_dir_all(&project_dir).unwrap();

        fs::write(
            project_dir.join("agent-noise.jsonl"),
            r#"{"type":"user","cwd":"/tmp/demo","timestamp":"2026-01-01T00:00:00Z","message":{"role":"user","content":"Your task is to inspect files"}}"#,
        )
        .unwrap();
        fs::write(
            project_dir.join("session-1.jsonl"),
            r#"{"type":"user","cwd":"/tmp/demo","timestamp":"2026-01-01T00:00:00Z","message":{"role":"user","content":"/compact keep key decisions"}}"#,
        )
        .unwrap();

        let store = ProjectStore::from_claude_dir_for_tests(claude_dir);
        let projects = store.list_projects().unwrap();

        assert_eq!(projects.len(), 1);
        assert_eq!(projects[0].sessions, vec!["session-1".to_string()]);
    }

    #[test]
    fn session_summary_filters_slash_command_only_prompt() {
        let tmp = tempfile::tempdir().unwrap();
        let session_path = tmp.path().join("session.jsonl");
        fs::write(
            &session_path,
            r#"{"type":"user","timestamp":"2026-01-01T00:00:00Z","message":{"role":"user","content":"/help"}}"#,
        )
        .unwrap();

        let summary = extract_session_summary(&session_path);
        assert!(summary.first_message.is_none());
        assert!(summary.last_message_timestamp.is_some());
    }

    #[test]
    fn session_summary_does_not_scan_tail_for_last_activity() {
        let tmp = tempfile::tempdir().unwrap();
        let session_path = tmp.path().join("session.jsonl");
        let mut lines = vec![
            r#"{"type":"system","subtype":"init","timestamp":"2026-01-01T00:00:00Z","model":"claude-opus"}"#.to_string(),
            r#"{"type":"user","timestamp":"2026-01-01T00:00:01Z","message":{"role":"user","content":"real first prompt"}}"#.to_string(),
        ];
        lines.extend((0..300).map(|idx| {
            format!(
                r#"{{"type":"assistant","timestamp":"2030-01-01T00:00:{:02}Z","message":{{"role":"assistant","content":"tail {}"}}}}"#,
                idx % 60,
                idx
            )
        }));
        fs::write(&session_path, lines.join("\n")).unwrap();

        let summary = extract_session_summary(&session_path);

        assert_eq!(summary.first_message.as_deref(), Some("real first prompt"));
        assert_eq!(summary.model.as_deref(), Some("claude-opus"));
        assert!(summary.last_message_timestamp.is_some());
        assert!(
            !summary
                .last_message_timestamp
                .as_deref()
                .unwrap()
                .starts_with("2030-01-01T00:00"),
            "session summaries should use file metadata for list activity instead of scanning long JSONL tails"
        );
    }
}
