use std::fs;
use std::io::{BufRead, BufReader};
use std::path::Path;
use std::time::SystemTime;

use chrono::{DateTime, Utc};
use serde_json::Value;

use super::models::JsonlEntry;
use super::paths::get_claude_dir;

/// 检查文本是否像一个独立的斜杠命令（如 /compact、/help、/cost）
fn is_slash_command_message(text: &str) -> bool {
    let trimmed = text.trim();
    trimmed.starts_with('/')
        && !trimmed.contains('\n')
        && trimmed.len() < 256
        && !trimmed.contains('\\')
        && trimmed.matches('/').count() == 1
}

/// 检查文本是否是内部自动压缩提示词
fn is_auto_compaction_instruction(text: &str) -> bool {
    let normalized = text
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .to_lowercase();

    normalized.starts_with(
        "focus on preserving key information, decisions made, and current context.",
    ) || normalized.starts_with(
        "preserve only the most critical information: current task, key decisions, and essential context.",
    ) || normalized.starts_with(
        "maintain comprehensive context while removing only obvious redundancies.",
    )
}

/// Extracts the first valid user message from a JSONL file
pub fn extract_first_user_message<P: AsRef<Path>>(
    jsonl_path: P,
) -> (Option<String>, Option<String>) {
    let file = match fs::File::open(jsonl_path) {
        Ok(file) => file,
        Err(_) => return (None, None),
    };

    let reader = BufReader::new(file);

    for line in reader.lines() {
        if let Ok(line) = line {
            if let Ok(entry) = serde_json::from_str::<JsonlEntry>(&line) {
                if let Some(message) = entry.message {
                    if message.role.as_deref() == Some("user") {
                        if let Some(content_value) = message.content {
                            // 提取文本内容（支持字符串和数组两种格式）
                            let mut extracted_text = String::new();
                            let mut has_text_content = false;

                            if let Some(text) = content_value.as_str() {
                                // 字符串格式
                                extracted_text = text.to_string();
                                has_text_content = !text.trim().is_empty();
                            } else if let Some(arr) = content_value.as_array() {
                                // 数组格式（可能包含 text 和 tool_result）
                                for item in arr {
                                    if let Some(item_type) =
                                        item.get("type").and_then(|t| t.as_str())
                                    {
                                        if item_type == "text" {
                                            if let Some(text) =
                                                item.get("text").and_then(|t| t.as_str())
                                            {
                                                extracted_text.push_str(text);
                                                has_text_content = true;
                                            }
                                        }
                                    }
                                }
                            }

                            // 必须有文本内容
                            if !has_text_content {
                                continue;
                            }

                            // Skip if it contains the caveat message
                            if extracted_text.contains("Caveat: The messages below were generated by the user while running local commands") {
                                continue;
                            }

                            // Skip if it starts with command tags
                            if extracted_text.starts_with("<command-name>")
                                || extracted_text.starts_with("<local-command-stdout>")
                            {
                                continue;
                            }

                            // Skip Warmup messages (auto-sent on session start)
                            if extracted_text.contains("Warmup") {
                                continue;
                            }

                            // Skip slash-command-only sessions (e.g. /compact, /help, /cost)
                            if is_slash_command_message(&extracted_text) {
                                continue;
                            }

                            // Skip internal auto-compaction prompts generated by the app
                            if is_auto_compaction_instruction(&extracted_text) {
                                continue;
                            }

                            // Found a valid user message
                            return (Some(extracted_text), entry.timestamp);
                        }
                    }
                }
            }
        }
    }

    (None, None)
}

/// Extracts the timestamp of the last message (user or assistant) from a JSONL file
#[allow(dead_code)]
pub fn extract_last_message_timestamp<P: AsRef<Path>>(jsonl_path: P) -> Option<String> {
    let file = match fs::File::open(jsonl_path) {
        Ok(file) => file,
        Err(_) => return None,
    };

    let reader = BufReader::new(file);
    let mut last_timestamp: Option<String> = None;

    for line in reader.lines() {
        if let Ok(line) = line {
            if let Ok(entry) = serde_json::from_str::<JsonlEntry>(&line) {
                // Check if this entry has a message (user or assistant)
                if entry.message.is_some() {
                    // Update last_timestamp if this entry has a timestamp
                    if let Some(timestamp) = entry.timestamp {
                        last_timestamp = Some(timestamp);
                    }
                }
            }
        }
    }

    last_timestamp
}

/// Extracts the model used in the session from a JSONL file
/// Looks for model information in system init messages or assistant messages
#[allow(dead_code)]
pub fn extract_session_model<P: AsRef<Path>>(jsonl_path: P) -> Option<String> {
    let file = match fs::File::open(jsonl_path) {
        Ok(file) => file,
        Err(_) => return None,
    };

    let reader = BufReader::new(file);
    let mut last_model: Option<String> = None;

    for line in reader.lines() {
        if let Ok(line) = line {
            // Try to parse as a generic JSON value first
            if let Ok(entry) = serde_json::from_str::<Value>(&line) {
                // Check for model in different locations:
                // 1. System init message: { "type": "system", "model": "..." }
                // 2. Assistant message: { "type": "assistant", "message": { "model": "..." } }

                if let Some(model_str) = entry.get("model").and_then(|m| m.as_str()) {
                    last_model = Some(model_str.to_string());
                } else if let Some(message) = entry.get("message") {
                    if let Some(model_str) = message.get("model").and_then(|m| m.as_str()) {
                        last_model = Some(model_str.to_string());
                    }
                }
            }
        }
    }

    last_model
}

fn sort_messages_chronologically_preserving_missing_timestamps(messages: Vec<Value>) -> Vec<Value> {
    let mut last_timestamp: Option<String> = None;
    let mut indexed: Vec<(usize, String, Value)> = Vec::with_capacity(messages.len());

    for (index, message) in messages.into_iter().enumerate() {
        let timestamp = message
            .get("timestamp")
            .and_then(|t| t.as_str())
            .filter(|t| !t.is_empty())
            .map(|t| {
                last_timestamp = Some(t.to_string());
                t.to_string()
            })
            .or_else(|| last_timestamp.clone())
            .unwrap_or_default();
        indexed.push((index, timestamp, message));
    }

    indexed.sort_by(|(ia, tsa, _), (ib, tsb, _)| tsa.cmp(tsb).then_with(|| ia.cmp(ib)));
    indexed.into_iter().map(|(_, _, message)| message).collect()
}

/// 为历史消息补充“展示/排序时间戳”（user 写 sentAt、assistant/system/result 写 receivedAt）。
///
/// 关键约束：必须优先使用消息自带的真实 `timestamp`，让 user 的 sentAt 与 assistant 的
/// receivedAt 落在**同一时钟**。否则前端排序键在 user(取真实 timestamp) 与
/// assistant(取本函数合成的 receivedAt) 之间会混用两套时间基准，导致带 UI-only 事件触发
/// 全量重排序时，所有用户消息被整体堆叠到会话顶部。
///
/// 仅当历史消息确实缺失 `timestamp`（极老的会话）时，才退回基于文件 mtime 的合成时间
/// （按行号每条间隔 5s 倒推），此时 user/assistant 同样落在这条合成时间线上，保持一致。
fn apply_display_timestamps_preferring_real(messages: &mut [Value], base_time: SystemTime) {
    let messages_count = messages.len();
    for (i, message) in messages.iter_mut().enumerate() {
        let message_type = message
            .get("type")
            .and_then(|t| t.as_str())
            .unwrap_or("")
            .to_string();

        // 优先真实 timestamp；缺失时才用 mtime 合成时间（越老的消息时间越早）。
        let timestamp_iso = message
            .get("timestamp")
            .and_then(|t| t.as_str())
            .filter(|t| !t.is_empty())
            .map(|t| t.to_string())
            .unwrap_or_else(|| {
                let time_offset = (messages_count - i - 1) as u64 * 5;
                let message_time = base_time - std::time::Duration::from_secs(time_offset);
                DateTime::<Utc>::from(message_time).to_rfc3339()
            });

        // 仅在对应字段缺失时写入，避免覆盖实时流已设置的真实时间。
        match message_type.as_str() {
            "user" => {
                if message.get("sentAt").is_none() {
                    message["sentAt"] = Value::String(timestamp_iso);
                }
            }
            _ => {
                if message.get("receivedAt").is_none() {
                    message["receivedAt"] = Value::String(timestamp_iso);
                }
            }
        }
    }
}

/// Loads the JSONL history for a specific session
/// Also loads subagent messages from agent-*.jsonl files and merges them
pub fn load_session_history(session_id: &str, project_id: &str) -> Result<Vec<Value>, String> {
    log::info!(
        "Loading session history for session: {} in project: {}",
        session_id,
        project_id
    );

    let claude_dir = get_claude_dir().map_err(|e| e.to_string())?;
    let project_dir = claude_dir.join("projects").join(project_id);
    let session_path = project_dir.join(format!("{}.jsonl", session_id));

    if !session_path.exists() {
        return Err(format!("Session file not found: {}", session_id));
    }

    // Get file modification time as base timestamp
    let file_metadata =
        fs::metadata(&session_path).map_err(|e| format!("Failed to read file metadata: {}", e))?;
    let base_time = file_metadata
        .modified()
        .unwrap_or_else(|_| SystemTime::now());

    let file =
        fs::File::open(&session_path).map_err(|e| format!("Failed to open session file: {}", e))?;

    let reader = BufReader::new(file);
    let mut messages = Vec::new();

    // Step 1: Load main session messages and build agentId -> tool_use_id mapping
    let mut agent_to_tool_use_id: std::collections::HashMap<String, String> =
        std::collections::HashMap::new();

    for line in reader.lines() {
        if let Ok(line) = line {
            if let Ok(json) = serde_json::from_str::<Value>(&line) {
                // Check for tool_result with agentId to build mapping
                if let Some(content) = json
                    .get("message")
                    .and_then(|m| m.get("content"))
                    .and_then(|c| c.as_array())
                {
                    for item in content {
                        if item.get("type").and_then(|t| t.as_str()) == Some("tool_result") {
                            // Get tool_use_id and agentId from toolUseResult
                            if let (Some(tool_use_id), Some(agent_id)) = (
                                item.get("tool_use_id").and_then(|t| t.as_str()),
                                json.get("toolUseResult")
                                    .and_then(|r| r.get("agentId"))
                                    .and_then(|a| a.as_str()),
                            ) {
                                log::debug!(
                                    "Found agentId mapping: {} -> {}",
                                    agent_id,
                                    tool_use_id
                                );
                                agent_to_tool_use_id
                                    .insert(agent_id.to_string(), tool_use_id.to_string());
                            }
                        }
                    }
                }
                messages.push(json);
            }
        }
    }

    log::info!(
        "Found {} agent-to-tool_use_id mappings",
        agent_to_tool_use_id.len()
    );

    // Step 2: Load subagent messages from agent-*.jsonl files
    if !agent_to_tool_use_id.is_empty() {
        if let Ok(entries) = fs::read_dir(&project_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if let Some(file_name) = path.file_name().and_then(|n| n.to_str()) {
                    // Match agent-*.jsonl files
                    if file_name.starts_with("agent-") && file_name.ends_with(".jsonl") {
                        // Extract agentId from filename (e.g., "agent-aa740fde.jsonl" -> "aa740fde")
                        let agent_id = file_name
                            .strip_prefix("agent-")
                            .and_then(|s| s.strip_suffix(".jsonl"))
                            .unwrap_or("");

                        // Check if this agent belongs to our session
                        if let Some(tool_use_id) = agent_to_tool_use_id.get(agent_id) {
                            log::info!(
                                "Loading subagent file: {} for tool_use_id: {}",
                                file_name,
                                tool_use_id
                            );

                            // Load subagent messages
                            if let Ok(file) = fs::File::open(&path) {
                                let reader = BufReader::new(file);
                                for line in reader.lines() {
                                    if let Ok(line) = line {
                                        if let Ok(mut json) = serde_json::from_str::<Value>(&line) {
                                            // Verify this subagent belongs to our session
                                            let subagent_session_id =
                                                json.get("sessionId").and_then(|s| s.as_str());
                                            if subagent_session_id == Some(session_id) {
                                                // Add parent_tool_use_id to link subagent messages to Task
                                                json["parent_tool_use_id"] =
                                                    Value::String(tool_use_id.clone());
                                                messages.push(json);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    // Step 3: Sort messages by timestamp to maintain chronological order.
    //
    // jsonl 的物理行序本身是正确写入顺序；子代理消息（Step 2）append 到末尾后
    // 需要按 timestamp 插回主时间线。但缺失 timestamp 的历史消息不能用空串排序，
    // 否则会被整体甩到顶部。这里给缺失 timestamp 的消息继承“前一条有时间消息”
    // 的排序键，并用原始行号兜底，既保持总排序稳定，也避免旧消息错位。
    let mut messages = sort_messages_chronologically_preserving_missing_timestamps(messages);

    // Step 4: 为缺失展示时间戳的历史消息补充 sentAt/receivedAt。
    // 必须优先采用消息自带的真实 timestamp，确保 user 与 assistant 落在同一时钟，
    // 否则前端按 receivedAt||timestamp||sentAt 排序时会混用两套时间基准，把用户消息堆到顶部。
    apply_display_timestamps_preferring_real(&mut messages, base_time);

    log::info!(
        "Loaded {} total messages (including subagent messages)",
        messages.len()
    );
    Ok(messages)
}

#[cfg(test)]
mod tests {
    use super::{
        apply_display_timestamps_preferring_real, is_auto_compaction_instruction,
        is_slash_command_message, sort_messages_chronologically_preserving_missing_timestamps,
    };
    use serde_json::{json, Value};
    use std::time::SystemTime;

    fn ids(messages: &[Value]) -> Vec<&str> {
        messages
            .iter()
            .map(|m| m.get("id").and_then(|id| id.as_str()).unwrap())
            .collect()
    }

    #[test]
    fn detects_slash_command_messages() {
        assert!(is_slash_command_message("/compact keep key decisions"));
        assert!(is_slash_command_message("/help"));
        assert!(!is_slash_command_message("D:/work/project"));
        assert!(!is_slash_command_message("https://example.com"));
        assert!(!is_slash_command_message("normal prompt"));
    }

    #[test]
    fn detects_internal_auto_compaction_prompts() {
        assert!(is_auto_compaction_instruction(
            "Focus on preserving key information, decisions made, and current context. Remove redundant explanations."
        ));
        assert!(is_auto_compaction_instruction(
            "Preserve only the most critical information: current task, key decisions, and essential context."
        ));
        assert!(!is_auto_compaction_instruction(
            "Please summarize this bug report for me."
        ));
    }

    #[test]
    fn history_sort_preserves_missing_timestamp_order() {
        let messages = vec![
            json!({ "id": "user-1", "type": "user", "timestamp": "2026-01-01T00:00:00Z" }),
            json!({ "id": "assistant-1", "type": "assistant" }),
            json!({ "id": "user-2", "type": "user" }),
            json!({ "id": "assistant-2", "type": "assistant", "timestamp": "2026-01-01T00:01:00Z" }),
        ];

        let sorted = sort_messages_chronologically_preserving_missing_timestamps(messages);

        assert_eq!(
            ids(&sorted),
            vec!["user-1", "assistant-1", "user-2", "assistant-2"]
        );
    }

    #[test]
    fn history_sort_inserts_late_loaded_subagent_by_timestamp() {
        let messages = vec![
            json!({ "id": "user-1", "type": "user", "timestamp": "2026-01-01T00:00:00Z" }),
            json!({ "id": "assistant-1", "type": "assistant", "timestamp": "2026-01-01T00:02:00Z" }),
            json!({ "id": "subagent", "type": "assistant", "timestamp": "2026-01-01T00:01:00Z" }),
        ];

        let sorted = sort_messages_chronologically_preserving_missing_timestamps(messages);

        assert_eq!(ids(&sorted), vec!["user-1", "subagent", "assistant-1"]);
    }

    // 回归测试：真实会话每条消息都自带 timestamp。补充展示时间戳时必须直接采用真实
    // timestamp，使 user 的 sentAt 与 assistant 的 receivedAt 落在同一时钟，否则前端
    // 混用两套时间基准会把所有用户消息堆到会话顶部。
    #[test]
    fn display_timestamps_prefer_real_timestamp_same_clock() {
        let mut messages = vec![
            json!({ "type": "user", "timestamp": "2026-06-04T12:15:26.165Z" }),
            json!({ "type": "assistant", "timestamp": "2026-06-04T12:15:32.270Z" }),
            json!({ "type": "user", "timestamp": "2026-06-04T12:15:33.142Z" }),
            json!({ "type": "assistant", "timestamp": "2026-06-04T12:15:38.243Z" }),
        ];

        apply_display_timestamps_preferring_real(&mut messages, SystemTime::now());

        // user 写入 sentAt 且等于真实 timestamp
        assert_eq!(
            messages[0].get("sentAt").and_then(|v| v.as_str()),
            Some("2026-06-04T12:15:26.165Z")
        );
        assert_eq!(
            messages[2].get("sentAt").and_then(|v| v.as_str()),
            Some("2026-06-04T12:15:33.142Z")
        );
        // assistant 写入 receivedAt 且等于真实 timestamp（与 user 同一时钟）
        assert_eq!(
            messages[1].get("receivedAt").and_then(|v| v.as_str()),
            Some("2026-06-04T12:15:32.270Z")
        );
        assert_eq!(
            messages[3].get("receivedAt").and_then(|v| v.as_str()),
            Some("2026-06-04T12:15:38.243Z")
        );

        // 前端排序键 receivedAt||timestamp||sentAt 对全体严格递增，user 不会被甩到顶部。
        let key = |m: &Value| {
            m.get("receivedAt")
                .or_else(|| m.get("timestamp"))
                .or_else(|| m.get("sentAt"))
                .and_then(|v| v.as_str())
                .unwrap()
                .to_string()
        };
        let keys: Vec<String> = messages.iter().map(key).collect();
        let mut sorted_keys = keys.clone();
        sorted_keys.sort();
        assert_eq!(keys, sorted_keys, "排序键应已是升序，时间线连贯");
    }

    // 极老会话缺失 timestamp 时，退回 mtime 合成时间线，user/assistant 仍落在同一时钟。
    #[test]
    fn display_timestamps_fallback_keeps_user_and_assistant_consistent() {
        let mut messages = vec![
            json!({ "type": "user" }),
            json!({ "type": "assistant" }),
            json!({ "type": "user" }),
        ];

        apply_display_timestamps_preferring_real(&mut messages, SystemTime::now());

        let t0 = messages[0].get("sentAt").and_then(|v| v.as_str()).unwrap();
        let t1 = messages[1]
            .get("receivedAt")
            .and_then(|v| v.as_str())
            .unwrap();
        let t2 = messages[2].get("sentAt").and_then(|v| v.as_str()).unwrap();

        // 合成时间线随行号递增（越早的消息时间越早）
        assert!(t0 < t1, "第0条应早于第1条");
        assert!(t1 < t2, "第1条应早于第2条");
    }

    // 已存在 sentAt/receivedAt（实时流写入）时不得被覆盖。
    #[test]
    fn display_timestamps_do_not_overwrite_existing() {
        let mut messages = vec![
            json!({ "type": "user", "timestamp": "2026-06-04T12:15:26.165Z", "sentAt": "real-sent" }),
            json!({ "type": "assistant", "timestamp": "2026-06-04T12:15:32.270Z", "receivedAt": "real-received" }),
        ];

        apply_display_timestamps_preferring_real(&mut messages, SystemTime::now());

        assert_eq!(
            messages[0].get("sentAt").and_then(|v| v.as_str()),
            Some("real-sent")
        );
        assert_eq!(
            messages[1].get("receivedAt").and_then(|v| v.as_str()),
            Some("real-received")
        );
    }
}
